---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-php-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 0.0.0.0
    path: /site
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-php-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 5Gi
